<?php

declare(strict_types=1);

namespace MarkupCarve\Carve\Test\TestCase\Parser;

use MarkupCarve\Carve\CarveConverter;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

class ColonFenceAuthoredBaseTest extends TestCase
{
    /**
     * @return array<array{string, string}>
     */
    public static function cases(): array
    {
        return [
            ["- head\n\n      ::: box\n      a\n   :::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n   ::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n::::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n   :::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n:::::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n    :::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n    ::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n::::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n    :::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n:::::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n     :::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n     ::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n::::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n     :::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a\n:::::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n      :::\n\n  tail\n", "<ul>\n  <li><p>head</p>\n    <div class=\"box\">\n      <p>a</p>\n    </div>\n    <p>tail</p>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n      ::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a</p>\n      <div>\n        <p>tail</p>\n      </div>\n    </div>\n  </li>\n</ul>\n"],
            ["- head\n\n      ::: box\n      a\n      :::::\n\n  tail\n", "<ul>\n  <li>head\n    <div class=\"box\">\n      <p>a</p>\n      <div>\n        <p>tail</p>\n      </div>\n    </div>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n     :::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n:::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n     ::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n::::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n     :::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n:::::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n      :::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n:::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n      ::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n::::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n      :::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n:::::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n       :::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n:::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n       ::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n::::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n       :::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a\n:::::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n        :::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li><p>head</p>\n        <div class=\"box\">\n          <p>a</p>\n        </div>\n        <p>tail</p>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n        ::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a</p>\n          <div>\n            <p>tail</p>\n          </div>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        ::: box\n        a\n        :::::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div class=\"box\">\n          <p>a</p>\n          <div>\n            <p>tail</p>\n          </div>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>    :::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>    ::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n::::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>    :::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n:::::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>     :::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>     ::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n::::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>     :::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n:::::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>      :::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>      ::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n::::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>      :::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a\n:::::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>       :::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li><p>head</p>\n      <div class=\"box\">\n        <p>a</p>\n      </div>\n      <p>tail</p>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>       ::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a</p>\n        <div>\n          <p>tail</p>\n        </div>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["> - head\n> \n>       ::: box\n>       a\n>       :::::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div class=\"box\">\n        <p>a</p>\n        <div>\n          <p>tail</p>\n        </div>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n   :::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n   ::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n::::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n   :::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n:::::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n    :::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n    ::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n::::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n    :::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n:::::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n     :::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n     ::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n::::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n     :::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a\n:::::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n      :::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a</p>\n      </div>\n      <p>tail<a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n      ::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a</p>\n        <div>\n          <p>tail</p>\n        </div>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            ["x[^n]\n\n[^n]: head\n\n      ::: box\n      a\n      :::::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div class=\"box\">\n        <p>a</p>\n        <div>\n          <p>tail</p>\n        </div>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n    :::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n    ::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n::::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n    :::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n:::::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n     :::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n     ::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n::::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n     :::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n:::::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n      :::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n      ::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n::::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n      :::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a\n:::::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n       :::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a</p>\n    </div>\n    <p>tail</p>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n       ::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a</p>\n      <div>\n        <p>tail</p>\n      </div>\n    </div>\n  </dd>\n</dl>\n"],
            [":: term\n:  head\n\n       ::: box\n       a\n       :::::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div class=\"box\">\n      <p>a</p>\n      <div>\n        <p>tail</p>\n      </div>\n    </div>\n  </dd>\n</dl>\n"],
            ["- head\n\n      :::\n      a\n    :::\n\n  tail\n", "<ul>\n  <li>head\n    <div>\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </li>\n</ul>\n"],
            ["- outer\n  - head\n\n        :::\n        a\n      :::\n\n    tail\n", "<ul>\n  <li>outer\n    <ul>\n      <li>head\n        <div>\n          <p>a\n:::</p>\n          <p>tail</p>\n        </div>\n      </li>\n    </ul>\n  </li>\n</ul>\n"],
            ["> - head\n> \n>       :::\n>       a\n>     :::\n> \n>   tail\n", "<blockquote>\n  <ul>\n    <li>head\n      <div>\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n    </li>\n  </ul>\n</blockquote>\n"],
            ["x[^n]\n\n[^n]: head\n\n      :::\n      a\n    :::\n\n  tail\n", "<p>x<a id=\"fnref1\" href=\"#fn1\" role=\"doc-noteref\"><sup>1</sup></a></p>\n<section role=\"doc-endnotes\" aria-label=\"Footnotes\">\n  <hr>\n  <ol>\n    <li id=\"fn1\">\n      <p>head</p>\n      <div>\n        <p>a\n:::</p>\n        <p>tail</p>\n      </div>\n      <p><a href=\"#fnref1\" role=\"doc-backlink\" aria-label=\"Back to reference\">↩</a></p>\n    </li>\n  </ol>\n</section>\n"],
            [":: term\n:  head\n\n       :::\n       a\n     :::\n\n   tail\n", "<dl>\n  <dt>term</dt>\n  <dd>\n    <p>head</p>\n    <div>\n      <p>a\n:::</p>\n      <p>tail</p>\n    </div>\n  </dd>\n</dl>\n"],
            ["- head\n\n      :::\n      a\n      ::::\n      b\n    :::\n      ::::\n      :::\n\n  tail\n", "<ul>\n  <li><p>head</p>\n    <div>\n      <p>a</p>\n      <div>\n        <p>b\n:::</p>\n      </div>\n    </div>\n    <p>tail</p>\n  </li>\n</ul>\n"],
            ["- head\n\n      :::\n      a\n      ```\n      :::\n      ```\n      :::\n\n  tail\n", "<ul>\n  <li><p>head</p>\n    <div>\n      <p>a</p>\n      <pre><code>:::\n</code></pre>\n    </div>\n    <p>tail</p>\n  </li>\n</ul>\n"],
            ["- head\n\n      :::\n      a\n      ~~~\n    :::\n      ~~~\n      :::\n\n  tail\n", "<ul>\n  <li><p>head</p>\n    <div>\n      <p>a</p>\n      <pre><code>  :::\n</code></pre>\n    </div>\n    <p>tail</p>\n  </li>\n</ul>\n"],
            ["- head\n\n      :::\n      a\n      :::: inner\n      b\n    :::::\n      ::::\n      :::\n\n  tail\n", "<ul>\n  <li><p>head</p>\n    <div>\n      <p>a</p>\n      <div class=\"inner\">\n        <p>b\n:::::</p>\n      </div>\n    </div>\n    <p>tail</p>\n  </li>\n</ul>\n"],
        ];
    }

    #[DataProvider('cases')]
    public function testCloserUsesAuthoredBase(string $source, string $expected): void
    {
        self::assertSame($expected, (new CarveConverter())->convert($source));
    }
}
